on:
  release:
    types: [created]

name: Deploy to Amazon Elastic beanstalk

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Beanstalk Deploy
      # You may pin to the exact commit or the version.
      # uses: einaregilsson/beanstalk-deploy@51975e958fd587756b6dc8a299d94cc16128af2f
      uses: einaregilsson/beanstalk-deploy@v14
      with:
       # AWS Access Key
       aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
       # AWS Secret Key
       aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       # AWS Region
       region: frankfurt 
       # Beanstalk application name
       application_name: OwinTest
       # Version label for new Beanstalk version
       version_label: 1
      
